App\Entity\Booking:
  attributes:
    pagination_items_per_page: 10
    normalization_context:
      groups: ['read']
    denormalization_context:
      groups: ['write']
  collectionOperations:
    get: ~
    post: ~
  itemOperations:
    get: ~
    put: ~
    delete: ~
    confirm_order:
        method: GET
        path: /order-confirmation
        controller: App\Controller\ConfirmBooking
        formats:
          json: ['application/json']
        read: false
    cancel_order:
        method: GET
        path: /order-cancelation
        controller: App\Controller\CancelBooking
        formats:
          json: ['application/json']
        read: false
  properties:
    booking-item:
      subresource:
        resourceClass: 'App\Entity\BookingItem'
        collection: true
