App\Entity\User:
  attributes:
    pagination_items_per_page: 10
    normalization_context:
      groups: ['read']
    denormalization_context:
      groups: ['write']
  collectionOperations:
    get: ~
    post: ~
  itemOperations:
    token_check:
        method: GET
        path: /users/token
        controller: App\Controller\CheckUserToken
        formats:
          json: ['application/json']
        read: false
    get: ~
    put: ~
    delete: ~
