# Configuration dynamique

[http.middlewares]
  [http.middlewares.redirect.redirectScheme]
    scheme = "https"
    
[tls]
  [[tls.certificates]]
    certFile = "/certs/local-cert.pem"
    keyFile = "/certs/local-key.pem"
